# cvedex - authoritative DNS server for the CVE corpus
# nginx proxy address - http://172.17.0.1:64580

name: cvedex

x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  cvedex:
    image: ghcr.io/casapps/cvedex:latest
    container_name: cvedex-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      - MODE=production
      - PORT=80
      - DEBUG=false
      - TZ=${TZ:-America/New_York}
    volumes:
      - './volumes/config:/config:z'
      - './volumes/data:/data:z'
    ports:
      - '172.17.0.1:64580:80'
    healthcheck:
      test: /usr/local/bin/cvedex --status
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - cvedex

networks:
  cvedex:
    name: cvedex
    external: false
